#ifndef TENSORFLOW_LITE_MICRO_EXAMPLES_PERSON_DETECTION_CONFIG_H_
#define TENSORFLOW_LITE_MICRO_EXAMPLES_PERSON_DETECTION_CONFIG_H_

// VFlip (Bật nếu hình ảnh bị lật dọc, tùy chọn - thử nghiệm để kiểm tra)
#define CONFIG_CAMERA_VFLIP 1

// Select device
// Chỉ chọn một model, ở đây là AI-Thinker cho ESP32-CAM
#define CONFIG_CAMERA_MODEL_AI_THINKER 1
// #define CONFIG_CAMERA_MODEL_WROVER_KIT 1
// #define CONFIG_CAMERA_MODEL_ESP_EYE 1
// #define CONFIG_CAMERA_MODEL_M5STACK_PSRAM 1
// #define CONFIG_CAMERA_MODEL_M5STACK_WIDE 1
// #define CONFIG_CAMERA_MODEL_CUSTOM 1

#endif // TENSORFLOW_LITE_MICRO_EXAMPLES_PERSON_DETECTION_CONFIG_H_